name: Go

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - uses: arduino/setup-protoc@v1

      - name: Installing protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - name: Generating protos
        run: |
          protoc -I=$PROTO_DIR \ 
          --go_out=$GEN_OUT_DIR \ 
          --go-grpc_out=$GEN_OUT_DIR \
          $(find $PROTO_DIR -type f -name '*.proto')
        env:
          GEN_OUT_DIR: internal/proto
          PROTO_DIR: internal/proto

      - name: Install Mockery
        run: |
          go get github.com/vektra/mockery/.../

      - name: Build
        working-directory: ./
        run: |
          go mod tidy
          go generate -x ./...
          go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./

      - name: Unit tests
        working-directory: ./
        run: |
          go mod tidy
          go test ./... -v -race -coverpkg=./...
