name: Go

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Install Protoc
        run: |
          mkdir -p $HOME/protoc
          curl -sSL https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-linux-x86_64.zip -o protoc.zip
          unzip protoc.zip -d $HOME/protoc
          export PATH=$HOME/protoc/bin:$PATH

      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Install Mockery
        run: |
          go get github.com/vektra/mockery/.../

      - name: Build
        working-directory: ./
        run: |
          go mod tidy
          go generate -x ./...
          go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./

      - name: Unit tests
        working-directory: ./
        run: |
          go mod tidy
          go test ./... -v -race -coverpkg=./...
