name: Go

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Install Protoc
        run: |
          sudo apt install protobuf-compiler

      - name: Install Mockery
        run: |
          sudo apt-get -y install mockery

      - name: Build
        working-directory: ./
        run: |
          go generate -x ./...
          go mod tidy
          go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./

      - name: Unit tests
        working-directory: ./
        run: |
          go mod tidy
          go test ./... -v -race -coverpkg=./...
